In [1]:
import torch

## All about pytorch tensors

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
my_ten =  torch.tensor(
    [[1,2,3], [7,8,9]],
     dtype=torch.float32, device=device,
     requires_grad=True)

In [4]:
print(my_ten)

tensor([[1., 2., 3.],
        [7., 8., 9.]], device='cuda:0', requires_grad=True)


In [5]:
type(my_ten)

torch.Tensor

In [6]:
print('shape of tensor: ')
print(my_ten.shape)

shape of tensor: 
torch.Size([2, 3])


In [7]:
print('type of tensor: ' )
print(my_ten.dtype)

type of tensor: 
torch.float32


In [8]:
print('device of  tensor: ' )
print(my_ten.device)

device of  tensor: 
cuda:0


### Common init methods

In [9]:
# Initialise empty tensors
x = torch.empty(size = (3,3))

# Note: it does not initialize the value with zeroes rather some random values available
# in the memory. It may look like zeroes.

In [10]:
# Initialise tensor with zeros 
x = torch.zeros(size = (3,3))
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Initialise tensors and convert to other types (int, float, ...)

In [11]:
tensor = torch.arange(4) 
tensor

tensor([0, 1, 2, 3])

In [12]:
# convert to bool
print(tensor.bool())

tensor([False,  True,  True,  True])


In [13]:
# convert to short - int16
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [14]:
# convert to long - int64 (imp: mostly used)
print(tensor.long())

tensor([0, 1, 2, 3])


In [15]:
# convert to half - float16
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [16]:
# convert to float - float32 (imp: mostly used)
print(tensor.float().dtype)

torch.float32


In [17]:
# convert to double - float64
print(tensor.double().dtype)

torch.float64


### Array to tensor conversion and vice versa

In [18]:
import numpy as np

In [19]:
numpy_arr = np.array([1, 2, 3])
numpy_arr

array([1, 2, 3])

In [20]:
torch_tensor = torch.from_numpy(numpy_arr)
torch_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
# Back to numpy
torch_tensor.numpy()

array([1, 2, 3])

### Tensor Math and Comparision Operators

In [22]:
# Adition
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
print(x,y)

tensor([1, 2, 3]) tensor([9, 8, 7])


In [23]:
# way1
# Save the results in another empty placeholder
z1 = torch.empty(3)
torch.add(x,y, out=z1)
print(z1)


tensor([10., 10., 10.])


In [24]:
# way2
z2 = torch.add(x,y)
print(z2)

tensor([10, 10, 10])


In [25]:
z3 = x + y
print(z3)

tensor([10, 10, 10])


In [26]:
# Substraction
# all methods works but below is the simplest one
z = x-y
print(z)

tensor([-8, -6, -4])


In [27]:
# Substraction
# Legacy version
z = torch.true_divide(x, y) # does the element-wise division. It is a bit clunky.
print("legacy system:", z)

# updated system like the simple division
z = x/y
print("updated system:", z)

legacy system: tensor([0.1111, 0.2500, 0.4286])
updated system: tensor([0.1111, 0.2500, 0.4286])


In [28]:
# Inplace operations

# perform the operations and update the variable witout making a copy
# Any operations follwed by '_' does the inplace operation
# E.g., add_, subtract_, multiply_, normal_, uniform_

t = torch.zeros(3)
print('t :', t)

# observe the difference between below 2 operations
t.add(2)
print('\n add operation')
print('t :', t)

t.add_(2)
print('\n add_ operation')
print('t :', t)


t = t + 1 # makes a copy of t and then overwrites it
print('\n add operation')
print('t :', t)


t : tensor([0., 0., 0.])

 add operation
t : tensor([0., 0., 0.])

 add_ operation
t : tensor([2., 2., 2.])

 add operation
t : tensor([3., 3., 3.])


In [29]:
# exponential operations
z = x.pow(2)
print(z)

z = x**2 # prefered way. Easy and simple
print(z)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [30]:
# comparision operators
z = x < 3
print(z)

z = x > 3
(z)

tensor([ True,  True, False])


tensor([False, False, False])

In [31]:
# matrix multiplication operations

x1 = torch.rand(size=(1,4))
x2 = torch.rand(size=(4,3))

print(x1)
print(x2)

# matrix multiplication
print('\n matrix multiplication: ')
z = torch.mm(x1,x2) # ouput size: 1x3
print(z)

z = x1.mm(x2)
print(z)

tensor([[0.3304, 0.9211, 0.3361, 0.9327]])
tensor([[0.8986, 0.6160, 0.4696],
        [0.6181, 0.9993, 0.4321],
        [0.1986, 0.3558, 0.4611],
        [0.0508, 0.0111, 0.9510]])

 matrix multiplication: 
tensor([[0.9804, 1.2539, 1.5951]])
tensor([[0.9804, 1.2539, 1.5951]])


In [32]:
# matrix exponential

mat_exp = torch.ones(3,3) * 2
print('mat_exp =', mat_exp)


print('mat_exp =', mat_exp.matrix_power(2))

mat_exp = tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
mat_exp = tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])


In [33]:
# element wise multiplication
print(x,y)

z = x*y
print(z)

# Dot product
z = x.dot(y)
print(z)

tensor([1, 2, 3]) tensor([9, 8, 7])
tensor([ 9, 16, 21])
tensor(46)


In [34]:
# Batch matrix multiplication or 3d multiplication
batch = 32
n = 10
m = 20
p = 30

t1 = torch.ones(size = (batch, n, m)) * 2
t2 = torch.ones(size = (batch, m, p)) * 2

out1 = t1.bmm(t2) # output dim: batch x n x p

# or
out2 = torch.bmm(t1, t2)

# checking whether output is same
(out1==out2).all()


tensor(True)

In [44]:
# broadcasting
x1 = torch.ones((5,3))
x2 = torch.ones((1,3))*2

print(x1)
print(x2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.]])


In [45]:
z = x1 - x2 
z

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [47]:
# other usefull tensor operations
# sum across rows or columns using 'dim'
torch.sum(x1, dim=1)

tensor([3., 3., 3., 3., 3.])

In [53]:
# get the min or max across rows or columns
values, indices = torch.min(x1, dim=0)
values, indices = torch.max(x1, dim=0)

# get only indices 
indices = torch.argmax(x1, dim=0)


In [61]:
# mean operation
# mean operation typecast the input to float type automatically
torch.mean(x2, dim=1)

tensor([2.])

In [62]:
# element wise comparison 
print(x,y)
torch.eq(x,y)

tensor([1, 2, 3]) tensor([9, 8, 7])


tensor([False, False, False])

In [66]:
# sort operations
# returs the values and indices
torch.sort(x, dim=0, descending=True)

torch.return_types.sort(
values=tensor([3, 2, 1]),
indices=tensor([2, 1, 0]))

In [67]:
# similar to argmin and argmax but for sort operation
torch.argsort(x, dim=0, descending=True)

tensor([2, 1, 0])

In [71]:
# clamp operations 
# clip the values 
torch.clamp(x, min=0, max=2) # clip any value which is outside the range of min and max 

tensor([1, 2, 2])

In [82]:
x1 = torch.tensor([0,1,0,1,1,], dtype=torch.bool)
print(x1)

# check if all of the values are true
print(torch.any(x1))

# check if all of the values are true
print(torch.all(x1))

tensor([False,  True, False,  True,  True])
tensor(True)
tensor(False)


### Tensor indexing

In [88]:
batch_size = 10
feature_size = 20
p = 5

x1 = torch.rand((batch_size, feature_size, p))
x1.shape

torch.Size([10, 20, 5])

In [96]:
print(x1[0].shape)
print(x1[:, 0].shape)
print(x1[:, :, 0:1].shape)

torch.Size([20, 5])
torch.Size([10, 5])
torch.Size([10, 20, 1])


In [98]:
# Fancy indexing
x = torch.arange(10)
fancy_indices = [1,5]

# get the values from only faanncy indexing
x[[fancy_indices]]

tensor([1, 5])

In [101]:
# advance indexing 
x = torch.arange(10)
print(x[(x < 2) | (x >8)])

tensor([0, 1, 9])


### Reshaping

In [102]:
x = torch.arange(9)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [111]:
# method 1 reshape: more felxible and prefered 
x_3x3 = x.reshape(3,3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [110]:
# method 2 view: Faster but can have some issues as it works with contagious memory only. 
x_3x3 = x.view(3,3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [128]:
# flatten the array
# In pytotch '-1' will automatically understand the context  
print(x_3x3.view(-1))

# or 
print(x_3x3.reshape(-1))


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [134]:
# flatten the 3d array
x = torch.rand((5,4,3))
print(x.shape)
x.reshape(-1)

torch.Size([5, 4, 3])


tensor([0.2072, 0.0090, 0.3333, 0.5121, 0.8545, 0.0419, 0.6769, 0.6267, 0.8252,
        0.8245, 0.6496, 0.3290, 0.9017, 0.5844, 0.3315, 0.6923, 0.2107, 0.1464,
        0.5038, 0.0047, 0.4079, 0.3351, 0.1175, 0.1020, 0.3653, 0.5287, 0.6619,
        0.3453, 0.4553, 0.4391, 0.7854, 0.2554, 0.1115, 0.7786, 0.5186, 0.6416,
        0.1231, 0.2803, 0.8014, 0.0412, 0.2266, 0.5199, 0.6134, 0.6814, 0.1764,
        0.0942, 0.8660, 0.0475, 0.2635, 0.5759, 0.9375, 0.9963, 0.6548, 0.8347,
        0.9683, 0.0345, 0.1472, 0.7367, 0.1979, 0.0205])

In [139]:
# permute to reshape it
# Here we need to give the index of dimension rater than the dimension size
# Think of this as a special case for transforse but applicaple to more than only matrix(2d array)
z = x.permute(0,2,1)
print('before: ', x.shape)
print('after: ', z.shape)

before:  torch.Size([5, 4, 3])
after:  torch.Size([5, 3, 4])


In [117]:
# Concatenate
x1 = torch.rand((2,4))
x2 = torch.rand((2,4))

print(x1)
print(x2)

tensor([[0.3758, 0.0358, 0.3676, 0.0572],
        [0.9965, 0.4806, 0.2394, 0.3907]])
tensor([[0.0285, 0.0664, 0.6732, 0.4995],
        [0.6231, 0.5367, 0.2265, 0.9908]])


In [124]:
# Concatenate acroass columns
row_cat = torch.cat((x1, x2), dim=0)
print(row_cat.shape)
print(row_cat)

torch.Size([4, 4])
tensor([[0.3758, 0.0358, 0.3676, 0.0572],
        [0.9965, 0.4806, 0.2394, 0.3907],
        [0.0285, 0.0664, 0.6732, 0.4995],
        [0.6231, 0.5367, 0.2265, 0.9908]])


In [125]:
# Concatenate acroass columns
col_cat = torch.cat((x1, x2), dim=1)
print(col_cat.shape)
print(col_cat)

torch.Size([2, 8])
tensor([[0.3758, 0.0358, 0.3676, 0.0572, 0.0285, 0.0664, 0.6732, 0.4995],
        [0.9965, 0.4806, 0.2394, 0.3907, 0.6231, 0.5367, 0.2265, 0.9908]])


In [154]:
# unsqueze : adding dimension 
# squeeze : removing dimension

x = torch.arange(10)
print(x.shape, x)

z = x.unsqueeze(0)
print(z.shape)

z = x.unsqueeze(1)
print(z.shape)

z = x.unsqueeze(1).unsqueeze(1)
print(z.shape)

z = z.squeeze(1)
print(z.shape)


torch.Size([10]) tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([10, 1, 1])
torch.Size([10, 1])
